pipeline {
    agent any
    stages {
        stage('build') {
            steps {
                sh 'echo "test"'
            }
        }
        stage('test') {
            steps {
                sh "python --version"
            }
        }
    }
}
